### ISSUE TITLE
Using # instead of b

### ISSUE THREAD

**Issue by LuisRodriguezLD** [frigidrain/chord-transposer#2]
I can see the Transposer has preferences when transposing up or down.

For example, 
`Transposer.transpose('C').fromKey('C').up(1);`
returns Db

What if the user prefers `C#` as the answer?

Another example,
`Transposer.transpose('D').fromKey('D').down(1);`
returns C#

But again, what if the user prefers `Db`?
Is there a way to change this?

**Comment by frigidrain** [comment]
Hi Luis, I can't seem to reproduce the behaviour you are describing.

`Transposer.transpose('D').fromKey('D').down(1).text` returns `Db`

`Transposer.transpose('C').fromKey('C').up(1).text` returns `Db` as well.

Maybe you are using an older version of the code? Could you try updating to the latest version in npm and see if that solves your problem?

In both cases, the result should be Db because you are transposing to Db major. The transposer does not support uncommon key signatures like C# major.

**Comment by LuisRodriguezLD** [comment]
You are correct, updating did the trick!
Also, I managed to workaround the `#`. I just need to go up by one a key below. 

Normal use:
`Transposer.transpose('C G Am F').fromKey('C').up(1).text`
the result is Db Ab Bbm Gb

But if I use:
`Transposer.transpose('C G Am F').fromKey('B').up(1).text`
and the result is C# G# A#m F#

Both right answers.
